package JUnit.Phormer; // Generated by Selenium IDE

import java.util.*;
import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

public class AddNewPhotoTest {
  private static final String imagePath = "C:\\Users\\catap\\OneDrive\\Desktop\\PhormerImages\\image.jpeg";

  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void addNewPhoto() {
    driver.get("http://localhost/");
    driver.findElement(By.linkText("Admin")).click();

    driver.findElement(By.name("passwd")).click();
    driver.findElement(By.name("passwd")).sendKeys("admin");
    driver.findElement(By.cssSelector(".submit")).click();

    driver.findElement(By.linkText("Manage Photos")).click();
    driver.findElement(By.linkText("Add a new photo!")).click();
    driver.switchTo().frame(0);

    // TODO: imagePath deve essere per forza assoluto altrimenti abbiamo un'eccezione
    driver.findElement(By.id("fileAddr")).sendKeys(imagePath); // /home/mike/Scrivania/image.jpg

    driver.switchTo().defaultContent();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.cssSelector("td > .radio:nth-child(4)")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("New Image");
    driver.findElement(By.name("photoinfo")).click();
    driver.findElement(By.name("photoinfo")).sendKeys("Info");

    {
      WebElement element = driver.findElement(By.name("categ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }

    {
      WebElement element = driver.findElement(By.name("categ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    {
      WebElement element = driver.findElement(By.name("categ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }

    driver.findElement(By.name("desc")).sendKeys("Description");
    driver.findElement(By.cssSelector(".radio:nth-child(4)")).click();
    driver.findElement(By.name("photoinfo")).click();
    driver.findElement(By.name("photoinfo")).sendKeys("Info");
    driver.findElement(By.cssSelector(".inside > table td:nth-child(2) tbody")).click();

    driver.findElement(By.name("story")).click();
    {
      WebElement element = driver.findElement(By.name("story"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }

    driver.findElement(By.cssSelector(".submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".note_valid"));
      assert(!elements.isEmpty());
    }
  }
}