package JUnit.Phormer; // Generated by Selenium IDE

import java.util.*;
import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
// import org.open.selenium.JavascriptExecutor;

public class CommentTest {
  private WebDriver driver = new ChromeDriver();
  private Map<String, Object> vars;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  @Test
  public void comment() {
    driver.get("http://localhost/");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".submenu:nth-child(2) img")).click();
    vars.put("win3545", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3545").toString());
    driver.findElement(By.name("name")).sendKeys("Mike");
    driver.findElement(By.name("email")).sendKeys("m.fonseta@studenti.unina.it");
    driver.findElement(By.name("txt")).click();
    driver.findElement(By.name("txt")).sendKeys("Description");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();

    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ok_msg"));
      assert(!elements.isEmpty());
    }
  }
}