package JUnit.Phormer; // Generated by Selenium IDE

import org.junit.Test;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

public class CreateStoryTest {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js = (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void createStory() {
    driver.get("http://localhost/");
    driver.findElement(By.linkText("Admin")).click();

    driver.findElement(By.name("passwd")).click();
    driver.findElement(By.name("passwd")).sendKeys("admin");
    driver.findElement(By.cssSelector(".submit")).click();

    driver.findElement(By.linkText("Manage Stories")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("New story");
    driver.findElement(By.name("desc")).sendKeys("Story description");
    driver.findElement(By.cssSelector("tr:nth-child(5) .radio:nth-child(4)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(6) .radio:nth-child(4)")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector(".submit")).click();
    assertThat(driver.findElement(By.cssSelector(".note_valid")).getText(), is("Story \"New story\" added succesfully!"));
  }
}