package JUnit.Phormer; // Generated by Selenium IDE

import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

public class ModifyCategoryTest {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js = (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
  }

  @Test
  public void modifyCategory() {
    driver.get("http://localhost/");
    driver.findElement(By.linkText("Admin")).click();
    driver.findElement(By.linkText("Manage Categories")).click();
    driver.findElement(By.cssSelector("span:nth-child(10) > a:nth-child(1)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("New category Edit");
    driver.findElement(By.name("desc")).click();
    driver.findElement(By.name("desc")).sendKeys("Category description Edit");
    driver.findElement(By.name("list")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).click();
    driver.findElement(By.id("public")).click();
    driver.findElement(By.cssSelector(".submit")).click();
    assertThat(driver.findElement(By.cssSelector(".note_valid")).getText(), is("Category \\\"New category Edit\\\" edited succesfully!"));
  }
}