package JUnit.Phormer; // Generated by Selenium IDE

import java.util.*;
import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;


public class ModifyPhotoTest {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js = (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void modifyPhoto() {
    driver.get("http://localhost/");
    driver.findElement(By.linkText("Admin")).click();
    driver.findElement(By.linkText("Manage Photos")).click();
    driver.findElement(By.linkText("Edit")).click();
    driver.findElement(By.name("getcmnts")).click();
    driver.findElement(By.name("desc")).click();
    driver.findElement(By.name("desc")).sendKeys("Test Edit");
    driver.findElement(By.cssSelector(".submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".note_valid"));
      assert(!elements.isEmpty());
    }
  }
}