package JUnit.Phormer; // Generated by Selenium IDE

import java.util.*;
import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;


public class SelectRatePhotoTest {
  private WebDriver driver = new ChromeDriver();
  private Map<String, Object> vars;
  JavascriptExecutor js = (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  @Test
  public void selectRatePhoto() {
    driver.get("http://localhost//");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".submenu:nth-child(2) img")).click();
    vars.put("win3009", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3009").toString());
    {
      WebElement dropdown = driver.findElement(By.id("rateSelect"));
      dropdown.findElement(By.xpath("//option[. = '5: Excellent!']")).click();
    }
    assertThat(driver.findElement(By.id("rateStatus")).getText(), is("Your rating saved!"));
  }
}