package JUnit.Phormer; // Generated by Selenium IDE

import java.util.*;
import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;

public class Selectlast20Test {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js = (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void selectlast20() {
    driver.get("http://localhost/");
    {
      List<WebElement> elements = driver.findElements(By.linkText("20"));
      assert(!elements.isEmpty());
    }
  }
}