package JUnit.Dolibarr;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class CreateTicket1Test {
  private  WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver=driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createTicket1() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("password")).sendKeys("dolibarr");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("#mainmenua_ticket > .mainmenuaspan")).click();
    driver.findElement(By.cssSelector(".menu")).click();
    driver.findElement(By.xpath("//div[@id=\'id-left\']/div/div[2]/div[3]/a")).click();
    driver.findElement(By.id("subject")).sendKeys("Richiesta");
    driver.findElement(By.id("message")).sendKeys("Ho una domanda");
    driver.findElement(By.name("add")).click();
    driver.findElement(By.cssSelector(".center:nth-child(3) > .butAction")).click();
    //Eliminazione del bottone
    driver.findElement(By.cssSelector(".ui-button:nth-child(1)")).click();
    driver.findElement(By.xpath("//div[@id=\'id-right\']/div/div[2]/div[3]/div/table/tbody/tr[7]/td/table/tbody/tr/td")).click();
    driver.findElement(By.xpath("//div[@id=\'id-right\']/div/div[2]/div[3]/div/table/tbody/tr[3]/td")).click();
    driver.findElement(By.xpath("//div[2]/div/div[2]/div/div/div[4]")).click();
    driver.findElement(By.xpath("//div[@id=\'id-right\']/div/div[2]/div/div/div[2]/span")).click();
    driver.findElement(By.xpath("//div[@id=\'id-right\']/div/div[2]/div[3]/div[2]/div")).click();
  }
}
