package JUnit.Dolibarr;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class DeleteBackup1Test {
  private  WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver=driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleteBackup1() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("password")).sendKeys("dolibarr");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".menu")).click();
    driver.findElement(By.linkText("Strumenti di amministrazione")).click();
    driver.findElement(By.cssSelector(".menu")).click();
    driver.findElement(By.linkText("Backup")).click();
    driver.findElement(By.id("radio_dump_mysql_nobin")).click();
    driver.findElement(By.id("buttonGo")).click();
    js.executeScript("window.scrollBy(0,600)", "");
    driver.findElement(By.xpath("//tr[@id=\'row-AFTER0POS1\']/td[6]/a/span")).click();
    driver.findElement(By.id("radio_dump_mysql_nobin")).click();
    driver.findElement(By.id("radio_dump_mysql")).click();
    driver.findElement(By.id("radio_dump_mysql_nobin")).click();
    driver.findElement(By.id("filename_template")).click();
    driver.findElement(By.id("radio_compression_gzip")).click();
    driver.findElement(By.id("radio_compression_none")).click();
  }
}
