package JUnit.Dolibarr;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class ReadAgenda1Test {
  private  WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver=driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void readAgenda1() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("password")).sendKeys("dolibarr");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".agenda")).click();
    driver.findElement(By.cssSelector(".fa-calendar-week")).click();
    driver.findElement(By.cssSelector(".fa-calendar-day")).click();

    driver.findElement(By.id("select2-search_projectid-container")).click();
    driver.findElement(By.id("selectsearch_status")).click();
    driver.findElement(By.id("select2-search_socid-container")).click();
    driver.findElement(By.id("select2-search_filtert-container")).click();
    driver.findElement(By.id("select2-search_actioncode-container")).click();
    driver.findElement(By.id("check_birthday")).click();
    driver.findElement(By.id("check_birthday")).click();
  }
}
