package JUnit.Dolibarr;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class UpdateValidityFile1Test {
  private  WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver=driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void updateValidityFile1() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("dolibarr");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".menu")).click();
    driver.findElement(By.linkText("Strumenti di amministrazione")).click();
    driver.findElement(By.cssSelector(".menu")).click();
    driver.findElement(By.linkText("Informazioni su Dolibarr")).click();
    driver.findElement(By.cssSelector(".menu")).click();
    driver.findElement(By.linkText("Verifica integrità dei file")).click();
    //Identificazione di un selettore da name a id
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".button")).click();
  }
}
