package JUnit.Dolibarr;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class UpdateStyle1Test {
  private  WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver=driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void updateStyle1() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("password")).sendKeys("dolibarr");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".home")).click();
    driver.findElement(By.cssSelector(".menu")).click();
    driver.findElement(By.linkText("Impostazioni")).click();
    driver.findElement(By.cssSelector(".menu")).click();
    driver.findElement(By.linkText("Menu")).click();
    driver.findElement(By.id("MAIN_MENU_STANDARD")).click();
    {
      WebElement dropdown = driver.findElement(By.id("MAIN_MENU_STANDARD"));
      dropdown.findElement(By.xpath("//option[. = 'auguria_menu']")).click();
    }
    driver.findElement(By.name("save")).click();
    driver.findElement(By.id("MAIN_MENU_STANDARD")).click();
    {
      WebElement dropdown = driver.findElement(By.id("MAIN_MENU_STANDARD"));
      dropdown.findElement(By.xpath("//option[. = 'eldy_menu']")).click();
    }
    driver.findElement(By.name("save")).click();




    driver.findElement(By.id("MAIN_MENU_STANDARD")).click();
    driver.findElement(By.id("MAIN_MENUFRONT_STANDARD")).click();
    driver.findElement(By.id("MAIN_MENU_SMARTPHONE")).click();
    driver.findElement(By.id("MAIN_MENUFRONT_SMARTPHONE")).click();
    driver.findElement(By.id("MAIN_MENU_STANDARD")).click();
    driver.findElement(By.id("MAIN_MENUFRONT_STANDARD")).click();
    driver.findElement(By.id("MAIN_MENU_SMARTPHONE")).click();
    driver.findElement(By.id("MAIN_MENUFRONT_SMARTPHONE")).click();
    driver.findElement(By.id("MAIN_MENU_STANDARD")).click();
    driver.findElement(By.id("MAIN_MENUFRONT_STANDARD")).click();
    driver.findElement(By.id("MAIN_MENU_SMARTPHONE")).click();
    driver.findElement(By.id("MAIN_MENUFRONT_SMARTPHONE")).click();
    driver.findElement(By.id("MAIN_MENU_STANDARD")).click();
    driver.findElement(By.id("MAIN_MENUFRONT_STANDARD")).click();
    driver.findElement(By.id("MAIN_MENU_SMARTPHONE")).click();
    driver.findElement(By.id("MAIN_MENUFRONT_SMARTPHONE")).click();
  }
}
