package JUnit.MantisBT;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class AddTag1Test {
  private  WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;


  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver=driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addTag1() {
    driver.get("http://localhost:8989/login_page.php");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.name("username")).sendKeys("Chris95");
    driver.findElement(By.cssSelector(".width-40")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".width-40")).click();
    //Selettore CSS troppo specifico
    driver.findElement(By.cssSelector(".my-buglist-bug:nth-child(1) .status-50-color")).click();
    driver.findElement(By.linkText("Le fatture sono errate")).click();
    driver.findElement(By.name("tag_string")).click();
    driver.findElement(By.name("tag_string")).sendKeys("mysql");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".bug-tags > .btn:nth-child(2)")).click();
  }
}
