package JUnit.MantisBT; // Generated by Selenium IDE

import java.util.List;
import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

public class CreateTag1Test {
  private  WebDriver driver = new ChromeDriver();
  JavascriptExecutor js = (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver=driver;
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void createTag1() throws InterruptedException {
    driver.get("http://localhost:8989/login_page.php");
    driver.manage().window().setSize(new Dimension(640, 480));

    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("administrator");
    driver.findElement(By.cssSelector(".width-40")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".width-40")).click();

    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".icon-bar:nth-child(4)")).click();

    Thread.sleep(1000);
    driver.findElement(By.cssSelector("li:nth-child(7) .menu-text")).click();
    driver.findElement(By.linkText("Gestisci etichette")).click();
    driver.findElement(By.id("tag-name")).click();
    driver.findElement(By.id("tag-name")).click();
    driver.findElement(By.id("tag-name")).sendKeys("-sd");
    driver.findElement(By.id("tag-description")).click();
    driver.findElement(By.id("tag-description")).click();
    driver.findElement(By.id("tag-description")).sendKeys("sadsadsa");
    driver.findElement(By.name("config_set")).click();

    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".widget-box:nth-child(1) .widget-title"));
      assert(!elements.isEmpty());
    }

    driver.close();
  }
}