package JUnit.MantisBT; // Generated by Selenium IDE

import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;

public class UpdateWorkflow1Test {
  private  WebDriver driver = new ChromeDriver();
  JavascriptExecutor js = (JavascriptExecutor) driver;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void updateWorkflow1() throws InterruptedException {
    driver.get("http://localhost:8989/login_page.php");
    driver.manage().window().setSize(new Dimension(640, 400));

    // Login as Administrator
    driver.findElement(By.id("username")).sendKeys("administrator");
    driver.findElement(By.cssSelector(".width-40")).click();
    driver.findElement(By.id("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".width-40")).click();

    // Test
    JavascriptExecutor executor = (JavascriptExecutor)driver;
    executor.executeScript("document.body.style.zoom = '0.9'");

    Thread.sleep(1000);
    driver.findElement(By.id("menu-toggler")).click();

    Thread.sleep(1000);
    WebElement element = driver.findElement(By.cssSelector("li:nth-child(7) .menu-text"));
    executor.executeScript("arguments[0].click();", element);

    Thread.sleep(1000);
    driver.findElement(By.linkText("Configurazione")).click();
    driver.findElement(By.linkText("Workflow")).click();
    driver.findElement(By.xpath("//form/div/input")).click();
    driver.close();
  }
}