package JUnit.JTrac; // Generated by Selenium IDE

import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

public class CreateSpaceTest {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) this.driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void createSpace() {
    driver.get("http://127.0.0.1:8888/app");

    // Login as Admin User
    driver.findElement(By.name("loginName")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("td:nth-child(3) > input")).click();

    // Test
    driver.findElement(By.linkText("OPZIONI")).click();
    driver.findElement(By.linkText("Gestione Spazi")).click();
    driver.findElement(By.linkText("Crea Nuovo Spazio")).click();

    driver.findElement(By.name("space.name")).sendKeys("My space");
    driver.findElement(By.name("space.prefixCode")).click();
    driver.findElement(By.name("space.prefixCode")).sendKeys("MFS");

    driver.findElement(By.name("space.description")).click();
    driver.findElement(By.name("space.description")).sendKeys("Description of my space");
    driver.findElement(By.name("space.guestAllowed")).click();

    driver.findElement(By.xpath("//input[@value=\'Avanti\']")).click();
    driver.findElement(By.name("next")).click();
    driver.findElement(By.name("save")).click();

    driver.findElement(By.linkText("OPZIONI")).click();
    driver.findElement(By.linkText("Gestione Spazi")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText(), is("My space"));
    driver.close();
  }
}