package JUnit.JTrac; // Generated by Selenium IDE

// import java.util.*;
import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

public class LoginAdminTest {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) this.driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void loginAdmin() {
    driver.get("http://127.0.0.1:8888/app");

    driver.findElement(By.name("loginName")).sendKeys("admin");

    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("admin");

    driver.findElement(By.cssSelector("td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("td > span")).click();

    WebElement elem = driver.findElement(By.cssSelector("td > span"));
    assertThat(elem.getText(), is("Admin"));

    /* // This test code does not work
      {
        List<WebElement> elements = driver.findElements(By.name("loginName"));
        assert(!elements.isEmpty());
      }
     */
    driver.close();
  }
}