package JUnit.JTrac; // Generated by Selenium IDE

import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

public class ModifyUser1Test {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) this.driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void modifyUser1() {
    driver.get("http://127.0.0.1:8888/app");

    // Login as Admin User
    driver.findElement(By.name("loginName")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("admin");
    driver.findElement(By.cssSelector("td:nth-child(3) > input")).click();

    // Test
    driver.findElement(By.linkText("OPZIONI")).click();
    driver.findElement(By.linkText("Gestione Utenti")).click();

    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    driver.findElement(By.xpath("//tr[4]/td[6]/a/img")).click();

    driver.findElement(By.name("user.loginName")).clear();
    driver.findElement(By.name("user.loginName")).sendKeys("13Mike");

    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("987654321");
    driver.findElement(By.name("passwordConfirm")).click();
    driver.findElement(By.name("passwordConfirm")).sendKeys("987654321");

    driver.findElement(By.xpath("//input[@value=\"Invia\"]")).click();
    assertThat(driver.findElement(By.cssSelector(".selected > td:nth-child(2)")).getText(), is("13Mike"));
    driver.close();
  }
}