package JUnit.Magento;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DeleteCart1Test {
  private WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;


  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleteCart1() throws InterruptedException {
    driver.get("http://localhost/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("#ui-id-3 > span")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".product-image-photo")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector("#product-addtocart-button > span")).click();
    Thread.sleep(2000);
    driver.findElement(By.linkText("shopping cart")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".action-delete")).click();
    driver.findElement(By.id("newsletter")).click();
    driver.findElement(By.id("search")).click();
    driver.findElement(By.id("search")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("newsletter")).click();
    driver.findElement(By.id("maincontent")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("newsletter")).click();
    driver.findElement(By.id("search")).click();
    driver.findElement(By.id("search")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("newsletter")).click();
    driver.findElement(By.id("maincontent")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("newsletter")).click();
    driver.findElement(By.id("maincontent")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
    driver.findElement(By.id("switcher-currency-trigger")).click();
  }
}
