package JUnit.Magento;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ReadView1Test {
  private WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;


  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void readView1() throws InterruptedException {
    driver.get("http://localhost/admin/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("username")).sendKeys("user");
    driver.findElement(By.id("login")).sendKeys("bitnami1");
    driver.findElement(By.cssSelector(".action-login > span")).click();
    driver.findElement(By.cssSelector("#menu-magento-catalog-catalog > a")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".item-catalog-products span")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath("//div[@id=\'container\']/div/div[2]/div/div[2]/div/button")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath("//fieldset/*[position() = 5]/div/select")).click();
    {
      //XPath troppo generico (Seleziona più elementi)
      WebElement dropdown = driver.findElement(By.name("store_id"));
      dropdown.findElement(By.xpath("//option[. = '            Default Store View']")).click();
    }
    driver.findElement(By.xpath("//div[2]/button")).click();
    driver.findElement(By.id("10")).click();
    driver.findElement(By.id("11")).click();
    driver.findElement(By.id("12")).click();
    driver.findElement(By.id("13")).click();
    driver.findElement(By.id("13")).click();
    driver.findElement(By.id("14")).click();
    driver.findElement(By.id("15")).click();
    driver.findElement(By.id("16")).click();
    driver.findElement(By.id("18")).click();
  }
}
