package JUnit.PasswordManager; // Generated by Selenium IDE

import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

public class DeleteEntry1Test {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void deleteEntry1() {
    driver.get("http://localhost:8000/");
    driver.findElement(By.id("user")).click();
    driver.findElement(By.id("user")).sendKeys("MikeFonseta");
    driver.findElement(By.id("pwd")).click();
    driver.findElement(By.id("pwd")).sendKeys("1231231");
    driver.findElement(By.id("chk")).click();

    driver.findElement(By.cssSelector(".datarow:nth-child(2) .glyphicon-wrench")).click();
    driver.findElement(By.id("delbtn")).click();

    driver.switchTo().alert().accept();
    driver.switchTo().alert().accept();

    assertThat(driver.findElement(By.cssSelector(".accountname")).getText(), is("Youtube"));
    driver.close();
  }
}