package JUnit.PasswordManager; // Generated by Selenium IDE

import java.time.Duration;
import java.util.*;
import org.junit.Test;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class DeleteEntry2Test {
  private WebDriver driver = new ChromeDriver();
  JavascriptExecutor js;

  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void deleteEntry2() throws InterruptedException {
    driver.get("http://localhost:8000/");
    driver.findElement(By.id("user")).click();
    driver.findElement(By.id("user")).sendKeys("MikeFonseta");
    driver.findElement(By.id("pwd")).click();
    driver.findElement(By.id("pwd")).sendKeys("1231231");
    driver.findElement(By.id("chk")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    WebElement elem = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".datarow:nth-child(2) .glyphicon-wrench")));
    elem.click();
    // driver.findElement(By.cssSelector(".datarow:nth-child(2) .glyphicon-wrench")).click();

    driver.findElement(By.id("delbtn")).click();

    Thread.sleep(2000);
    driver.switchTo().alert().accept();
    driver.switchTo().alert().accept();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".accountname"));
      assert(!elements.isEmpty());
    }
    driver.close();
  }
}